#!/usr/bin/env bash

# must run with sudo
if [[ $(id -u) -ne 0 ]] ; 
then 
    echo "Please run with sudo."
    exit 1
fi



for sh in *.sh
do
    echo
    echo "Applying +x permission to ${sh} ..."
    chmod --verbose +x "${sh}"
    echo
    echo "Copying ${sh} to /usr/local/bin ..."
    cp --force --verbose "${sh}" /usr/local/bin/
    echo
done

echo "Installer done."
